from fastapi import FastAPI
from fastapi.responses import FileResponse
from dotenv import load_dotenv
import requests
import os


load_dotenv()

app = FastAPI()

API_KEY = os.getenv("OPENROUTER_API_KEY")

print("API KEY LOADED:", API_KEY is not None)


@app.get("/")
def home():
    return FileResponse("static/index.html")


@app.get("/generate")
def generate_content(
    course_name: str,
    course_description: str,
    content_type: str,
    target_audience: str,
    platform: str,
    tone: str,
    language: str,
    goal: str,
    variations: int = 1
):

    prompt = f"""
You are an expert marketing copywriter specializing in educational courses,
training programs, academies, and online learning.

Your task is to create marketing content based ONLY on the information provided
by the user.

========================
COURSE INFORMATION
========================

Course Name:
{course_name}

Course Description:
{course_description}

Content Type:
{content_type}

Target Audience:
{target_audience}

Platform:
{platform}

Tone:
{tone}

Language:
{language}

Marketing Goal:
{goal}


========================
GENERAL RULES
========================

1. Use ONLY the information provided by the user.

2. NEVER invent:
- prices
- discounts
- offers
- certificates
- guarantees
- course duration
- number of students
- instructors
- support
- projects
- deadlines
- registration methods
- websites
- phone numbers
- testimonials
- results
- career opportunities
- salaries
- features that were not provided

3. Never make unsupported claims such as:
- "guaranteed results"
- "become an expert"
- "get a job"
- "double your income"
- "limited seats"
- "limited time"
unless the user explicitly provided that information.

4. Do not mention AI or say that the content was generated by AI.

5. Adapt the content to the selected platform.

6. Make the content natural and human-written.

7. Do not repeat the course name unnecessarily.

8. Avoid generic marketing clichés.

9. Do not make the content sound exaggerated or fake.

10. If a CTA is appropriate but no actual link or contact information was
provided, use a simple CTA without inventing a registration method.

11. If a placeholder is genuinely needed for a link, use:
[Course Link]

12. Write everything in the selected language.

13. If the language is Egyptian Arabic:
- Write natural Egyptian Arabic.
- Keep English technical terms in English.
- Never combine Arabic and English inside the same word.
- Do not create incorrect Arabic transliterations of English words.
- Make the writing sound like a real Egyptian marketer speaking naturally.


========================
CONTENT TYPE RULES
========================

IF CONTENT TYPE = "Social Media Post":

Create:

1. Hook
2. Main post
3. CTA
4. 5 relevant hashtags

The post should be suitable for the selected platform.

The hook should attract the target audience without making exaggerated claims.


IF CONTENT TYPE = "Advertisement":

Create a short promotional advertisement.

Structure:

- Strong headline
- Short description
- Main benefit based only on the provided course information
- CTA

Keep it concise and suitable for advertising.


IF CONTENT TYPE = "WhatsApp Message":

Create a short and friendly WhatsApp promotional message.

Rules:
- Keep it conversational.
- Do not make it sound like a formal advertisement.
- Avoid unnecessary long paragraphs.
- Include a natural CTA.


IF CONTENT TYPE = "Course Description":

Create a clear course description.

Structure:

- Short introduction
- What the course covers
- Who the course is for
- What the learner can expect to learn

Only mention information actually provided by the user.


IF CONTENT TYPE = "Content Ideas":

Generate exactly 10 creative content ideas.

For every idea provide:

1. Title
2. Short explanation
3. Suggested content format

The ideas should be relevant to the course and target audience.

Do not invent course features or claims.


========================
VARIATIONS
========================

Create {variations} different versions of the requested content.

Each version must:
- Use the same course information.
- Follow all rules above.
- Have a different hook, wording, or approach.
- Avoid repeating the exact same sentences.
- Keep the same factual information.

If variations = 1, generate only one version.

If variations > 1, clearly separate them using:

--- Variation 1 ---

--- Variation 2 ---

--- Variation 3 ---

and so on.


========================
FINAL QUALITY CHECK
========================

Before producing the final answer, check:

- Did I invent any course information?
- Did I add an unsupported claim?
- Did I use the correct content type?
- Did I follow the selected platform?
- Did I use the selected language?
- If Egyptian Arabic was selected, is the Arabic natural?
- Did I accidentally combine Arabic and English inside one word?
- Is the content actually useful for marketing?

If any answer is YES, fix it before returning the final content.

Return ONLY the final marketing content.
"""


    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }


    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers=headers,
        json={
            "model": "openrouter/free",
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        }
    )


    print("STATUS:", response.status_code)

    data = response.json()

    print("RESPONSE:", data)


    if response.status_code != 200:
        return {
            "error": data
        }


    if "choices" not in data:
        return {
            "error": "No AI response was returned."
        }


    return {
        "response": data["choices"][0]["message"]["content"]
    }